name: export-and-branch-solution
# Export solution from DEV environment
# Unpack it and prepare, commit, and push a git branch with the changes

on:
  workflow_dispatch:
    inputs:
      solution_name:
        description: 'Name of the solution to work on from Power Platform'
        required: true
        default: ALM Demo
      solution_exported_folder:
        description: 'Folder name for staging the exported solution (do not change)'
        required: true
        default: out/exported/
      solution_folder:
        description: 'Folder for unpacked solution before check-in (do not change)'
        required: true
        default: out/solutions/
      solution_target_folder: 
        description: 'Folder name to be created and checked in (do not change)'
        required: true
        default: solutions/

env:
  ENVIRONMENT_URL: '9b2bca3d-9b38-e892-bf71-a25ad854fe08'
  CLIENT_ID: 'aa8c8fdf-d042-4d00-9d11-87c38b268af2'
  TENANT_ID: 'bf59fe7f-17f4-4538-8014-69eff1fdadc8'

permissions:
  contents: write

jobs:
  export-from-dev:
    runs-on: windows-latest
    env:
      RUNNER_DEBUG: 1

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # REQUIRED: Install Power Platform CLI (PAC)
      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Validate authentication / connection
      - name: Who am I
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ env.TENANT_ID }}

      # Export solution from DEV
      - name: Export solution
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ env.ENVIRONMENT_URL }}
          app-id: ${{ env.CLIENT_ID }}
          client-secret: ${{ secrets.PowerPlatformSPN }}
          tenant-id: ${{ env.TENANT_ID }}
          solution-name: ${{ github.event.inputs.solution_name }}
          solution-output-file: >-
            ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip

      # Unpack solution
      - name: Unpack solution
        uses: microsoft/powerplatform-actions/unpack-solution@v1
        with:
          solution-file: >-
            ${{ github.event.inputs.solution_exported_folder }}/${{ github.event.inputs.solution_name }}.zip
          solution-folder: >-
            ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
          solution-type: Unmanaged
          overwrite-files: true

      # Create branch and commit solution changes
      - name: Create branch and prepare PR
        uses: microsoft/powerplatform-actions/branch-solution@v1
        with:
          solution-folder: >-
            ${{ github.event.inputs.solution_folder }}/${{ github.event.inputs.solution_name }}
          solution-target-folder: >-
            ${{ github.event.inputs.solution_target_folder }}/${{ github.event.inputs.solution_name }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty-commit: true
